### ISSUE TITLE
LocalFS::new/with_base_dir should be async

### ISSUE THREAD

**Issue by poelzi** [VivekPanyam/lunchbox#9]
Currently the constructor is sync and calls a sync fs method to check if the root exists.
Mixing sync and async calls in a lib should be avoided. I suggest changing to a async constructor.

**Comment by VivekPanyam** [comment]
Makes sense. Would you like to put up a PR? If not, I can take care of it this week.

Maybe something like

- `pub fn with_base_dir_unchecked(...)` that doesn't do the `is_dir` check
- `pub async fn with_base_dir(...)` that does an async `is_dir` check and then calls `Self::with_base_dir_unchecked`
- `pub fn new()` that calls `Self::with_base_dir_unchecked("/")` (since we don't really need to check if `/` is a directory)
